config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  resources :comments, only:[:index]
  resources :users, only:[:index]
    resources :speeches
    root 'users#index'
    get 'search', to: 'search#search'
    get 'speeches', to: 'speeches#all_comments'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :speech
end

app/models/speech.rb
class Speech < ApplicationRecord
  # include Elasticsearch::Model
  # include Elasticsearch::Model::Callbacks
  after_save :store_content!
  mount_uploader :content, ContentUploader
  validates :name, presence: true
  belongs_to :user, optional: true
  has_many :comments, :inverse_of => :speech
  has_many :users, through: :comments
  accepts_nested_attributes_for :comments, :reject_if => lambda { |a| a[:comment].blank? }, :allow_destroy => true

  # Speech.__elasticsearch__.create_index! force: true

  def self.highest_indexed

  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]
  validates :email, confirmation: true
  validates :password, length: { in: 6..20, message:'Your password must be between 6 and 20 characters' }
  has_many :comments
  has_many :speeches, through: :comments

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/callbacks_controller.rb
class CallbacksController < Devise::OmniauthCallbacksController
    def facebook
      @user = User.from_omniauth(request.env["omniauth.auth"])
      sign_in_and_redirect @user
    end
  end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @speech = Speech.all
  end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def search
    if params[:q].nil?
      @speeches = []
    else
     @speeches = Speech.search params[:q]
    end
  end
end

app/controllers/speeches_controller.rb
class SpeechesController < ApplicationController

  def index
    @speeches = Speech.reorder('created_at DESC').paginate(:page => params[:page], :per_page => 1)
    @comments = Comment.all
    @speech = current_user
  end

  def new
    @speech = Speech.new
    @comments = @speech.comments.build
  end

  def create
    speech_analysis
    speech = current_user.speeches.create(speech_params)
    if speech.content.content_type == "text/plain"
      ready = File.open(speech.content.current_path)
      speech.text_of_uploaded_content = ready.read
      speech.political_stats = Indico.political(speech.text_of_uploaded_content)
      speech.save
    elsif speech.content.content_type == "application/pdf"
      reader = PDF::Reader.new(speech.content.current_path)
      reader.pages.each do |page|
        doc_into_text = page.text.gsub(/[\s\n\b]/ ," ")
        no_bytes = doc_into_text.unpack('A*').to_s.gsub(/\\x[A-F0-9]{2}/,"")[2..-3]
        into_array = no_bytes.split(',')
        speech.text_of_uploaded_content = into_array.reject(&:empty?)
        speech.political_stats = Indico.political(speech.text_of_uploaded_content.to_s.gsub(/[\s,\""]/ , ""))
        speech.save
        #possibly adding the same process into a method and adding it to docx
      end
    # elsif speech.content.content_type == "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
    #     doc = Docx::Document.new(speech.content.current_path)
    #     doc.paragraphs.each do |page|
    #       speech.text_of_uploaded_content = page.text.gsub("\n",'')
    #      speech.save!
    #      speech.political_stats = Indico.political(speech.text_of_uploaded_content)
    #      speech.save!
    #     end
      end
      redirect_to speech_url(speech.id)
    end

  def show
    @speech = Speech.find(params[:id])
  end

  def edit
    @speech = Speech.find(params[:id])
  end

  def update
    @speech = Speech.find(params[:id])
    @comments = @speech.comments.all

    if @speech.update(speech_params)
      @speech.save
      redirect_to speeches_path
    else
      render "edit"
    end
  end

private

  def speech_params
    params.require(:speech).permit(:name, :content, :political_stats, :text_of_uploaded_content, comments_attributes: [:id, :title, :comment, :_destroy, :current_user])
  end

  def speech_analysis
    Indico.api_key = Rails.application.secrets.indico_api
  end

 #  def authenticate
 #    authenticate_or_request_with_http_basic do |indico_api|
 #     indico_api = Rails.application.secrets.indico_api
 #   end
 # end

  def all_comments
    @speech = Speech.new
    @comments = @speech.comments.build
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def all_users
    #add maybe user.active? user.speech.created_at > 1.hour.ago == active user.
    speech = Speech.all
    amount_unparsed = speech.map(&:user_id)
    @amount_of_parsed_users = amount_unparsed.uniq.count
  end
end

app/helpers/callbacks_helper.rb
module CallbacksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
  # def any_comments
  #   if @speech.comments.each do |comment|
  #      comments.comment.count == 0
  #      "No Comments"
  #   else
  #     "You Have Comments"
  #   end
  # end
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/speeches_helper.rb
module SpeechesHelper

  def political_percents
    string_numbers = @speech.political_stats.gsub(/[\s a-zA-Z{}=>""]/ , "").split(",")
    @liberatian = string_numbers[0].to_f
    @green = string_numbers[1].to_f
    @liberal = string_numbers[2].to_f
    @converative = string_numbers[3].to_f
    #I hate this!
  end

  def index_political_percent_helper
    @speeches.each do |speech|
      formated_stats = speech.political_stats.gsub(/[\s a-zA-Z{}=>""]/ , "").split(',')
      @liberatian = formated_stats[0]
      @green = formated_stats[1]
      @liberal = formated_stats[2]
      @converative = formated_stats[3]
    #I hate this even more!!
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/index.html.erb
<!--  -->

app/views/layouts/application.html.erb
 <%= content_tag(:div, flash[:error], :id => "flash_error") if flash[:error] %>
  <%= content_tag(:div, flash[:notice], :id => "flash_notice") if flash[:notice] %>
  <%= content_tag(:div, flash[:alert], :id => "flash_alert") if flash[:alert] %>

<%= favicon_link_tag '/charlie.jpg' %>
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">

    <%= link_to root_path do %>
     <%= image_tag "/charlie.jpg", :size => '80x150', :class => "navbar-brand" %>
     <%end%>

      <%= csrf_meta_tags %>
      <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_include_tag "https://www.google.com/jsapi" %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </div>

    <ul class="nav navbar-nav">
      <li class="active"><%=link_to 'Home', root_path%></li>
      <li><a href="#">About</a></li>
      <li><%= link_to 'All Speeches', speeches_path%></li>
      <li><%= link_to 'Create Speech', new_speech_path%></li>
      <li><%= link_to 'Search Speeches', search_path%></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Signup', new_user_registration_path, :class => "glyphicon glyphicon-user"%></li>
        <li><%= link_to 'Login', user_session_path, :class => "glyphicon glyphicon-log-in"%></li>
      <li><%= link_to 'Logout', destroy_user_session_path, method: :delete, :class => "glyphicon glyphicon-log-out"%></li>
    </ul>
  </div>
</nav>
<div class="footer navbar-fixed-bottom">
  <div class="container text-center">
  &copy Developed by Rafeeq Wilson
  </div>
</div>
<body>
  <%= yield %>
</body>

app/views/search/search.html.erb
<h1>Speeches Search</h1>

<%= form_for search_path, method: :get do |f| %>
  <p>
    <%= f.label "Search for" %>
    <%= text_field_tag :q, params[:q] %>
    <%= submit_tag "Go", name: nil %>
  </p>
<% end %>

<ul>
  <% @speeches.each do |speech| %>
    <li>
      <h3>
        <%= link_to speech.name, controller: " speeches", action: "show", id: speech._id%>
      </h3>
    </li>
  <% end %>
</ul>

app/views/speeches/_all_comments.html.erb
<div id="accordion" role="tablist" aria-multiselectable="true">
  <div class="card">
    <div class="card-header" role="tab" id="headingOne">
      <h5 class="mb-0">
        <button data-toggle="collapse" class="btn btn-primary"data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
          Leave a Comment
        </button>
      </h5>
    </div>
    <div id="collapseOne" class="collapse in" role="tabpanel" aria-labelledby="headingOne">
      <div class="card-block">
      <%= @speech.comments.each do |comment| %>
      <%=comment.comment%>
       <%end%>

      </div>
    </div>
  </div>

app/views/speeches/_comments_form.html.erb
<div id="accordion" role="tablist" aria-multiselectable="true">
  <div class="card">
    <div class="card-header" role="tab" id="headingOne">
      <h5 class="mb-0">
        <button data-toggle="collapse" class="btn btn-primary"data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
          Leave a Comment
        </button>
      </h5>
    </div>

    <div id="collapseOne" class="collapse in" role="tabpanel" aria-labelledby="headingOne">
      <div class="card-block">
        <%= form_for @speech do |f|%>
        <%= f.fields_for :comments do |comment| %>
        <%= comment.label :title%><br>
         <%= comment.text_field :title%><br>
        <%= comment.label :comment%><br>
        <%= comment.text_area :comment %><br>
        <%= f.submit "Leave a Comment"%>
        <%end%>
     <%end%>

    </div>
  </div>

app/views/speeches/_form.html.erb
<%= form_for @speech, html: {multipart: true} do |f| %>
<%= f.label :content%><br>
<%= f.file_field :content%>
<%= f.label :name%><br>
<%= f.text_field :name%><br>
<%= f.submit 'Upload Speech', class: "btn btn-primary"%>
<%end%>

app/views/speeches/_graph.html.erb
<%= line_chart [
  {name: "liberatian", data: number_to_percentage(@liberatian)},
  {name: "Green", data: number_to_percentage(@green)},
  {name: "liberal", data: number_to_percentage(@liberal)},
  {name: "Conservative", data: number_to_percentage(@converative)}

                              ] %>

app/views/speeches/_most.html.erb
<div id="accordion" role="tablist" aria-multiselectable="true">
  <div class="card">
    <div class="card-header" role="tab" id="headingOne">
      <h5 class="mb-0">
        <button data-toggle="collapse" class="btn btn-primary"data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
         Most Commented
        </button>
      </h5>
    </div>
    <div id="collapseOne" class="collapse in" role="tabpanel" aria-labelledby="headingOne">
    <div class="pre-scrollable">


      </div>
    </div>
  </div>
   </div>

app/views/speeches/edit.html.erb
<script src="http://responsivevoice.org/responsivevoice/responsivevoice.js"></script>
<script src="http://code.jquery.com/jquery-git2.js"></script>
<h3><%=@speech.name%></h3>

<textarea id="text" cols="45" rows="3">
<%= @speech.text_of_uploaded_content%></textarea>
</script>
<div>

</div>

<input onclick="responsiveVoice.speak($('#text').val(),$('#voiceselection').val());" type="button" value="Play"/>
<script type="text/javascript">
$("#text").on("click",function(){
  alert("The text will not be reavulated, please add a comment!");
});

</script>

<%= render partial: "speeches/comments_form"%>

app/views/speeches/index.html.erb
<div class="username">
<strong> Current User: <%=current_user.email%></strong>
<%all_users%>
<strong> Amount of Active Users: (<%=@amount_of_parsed_users %>), Help our community grow!</strong>
</div>
<%@speeches.each do |speech| %>
<strong><%=speech.name%></strong>
<strong><%= "Created on"%>  <%=speech.created_at.strftime("%B, %d, %Y")%></strong>
<div class="border_wrapper">
<% if speech.text_of_uploaded_content.nil? %>
  <%= "No content available"%>
<%else%>
  <%= speech.text_of_uploaded_content%>
</div>
<div>
  <label> Here is the analysis:</label><br>
  <%index_political_percent_helper%>

 <%= render partial: "speeches/graph"%>

</div>
  <%end%>
<%end%>


<div class="container text-center">
<%= will_paginate @speeches, renderer: BootstrapPagination::Rails %>
</div>

<%=link_to "Add Comment",edit_speech_path(@speeches.ids), :class =>"btn btn-primary"%>
<%=render partial: 'speeches/all_comments'%>

app/views/speeches/new.html.erb
<h6>Upload a Speech</h6>

<div class="new_wrapper">
  <%= render partial: "speeches/form"%>
</div>

app/views/speeches/show.html.erb
<script src="http://responsivevoice.org/responsivevoice/responsivevoice.js"></script>
<script src="http://code.jquery.com/jquery-git2.js"></script>
<h3>Name of Speech:<%=@speech.name%></h3>

<textarea id="text" cols="45" rows="3">
<%= @speech.text_of_uploaded_content%></textarea>
</script>
<div>

</div>

<input onclick="responsiveVoice.speak($('#text').val(),$('#voiceselection').val());" type="button" value="Play"/>
<%political_percents%>

<%= render partial: 'speeches/graph'%>
<%= render partial: "speeches/all_comments"%>